import { miniChartSvg } from "./mini-chart";
import { todayISO, uid } from "../utils";
import type { Account, JournalSnapshot, Plan, Timeframe, Trade } from "./types";
import { DEFAULT_APPEARANCE } from "./constants";

function at(daysAgo: number, hour: number, minute: number) {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function shots(seed: number, bull: boolean, tfs: Timeframe[]) {
  return tfs.map((timeframe, i) => ({
    id: `s_${seed}_${i}`,
    src: miniChartSvg(seed + i * 17, bull),
    timeframe,
  }));
}

const A1 = "acc_ftmo";
const A2 = "acc_personal";
const A3 = "acc_fp";

export const SEED_ACCOUNTS: Account[] = [
  {
    id: A1,
    name: "FTMO 100k",
    firm: "FTMO",
    type: "challenge",
    currency: "USD",
    startBalance: 100000,
    profitTargetPct: 10,
    maxDrawdownPct: 10,
    dailyLossPct: 5,
  },
  {
    id: A2,
    name: "Personal",
    firm: "Personal",
    type: "personal",
    currency: "USD",
    startBalance: 12500,
    profitTargetPct: 0,
    maxDrawdownPct: 8,
    dailyLossPct: 2,
  },
  {
    id: A3,
    name: "FundingPips 50k",
    firm: "FundingPips",
    type: "funded",
    currency: "USD",
    startBalance: 50000,
    profitTargetPct: 8,
    maxDrawdownPct: 6,
    dailyLossPct: 3,
  },
];

export function buildSeedTrades(): Trade[] {
  const rows: Array<Omit<Trade, "createdAt"> & { daysAgo: number }> = [
    {
      id: "t_today_1",
      daysAgo: 0,
      accountId: A1,
      title: "NQ Open Drive",
      pair: "NQ",
      market: "indices",
      side: "long",
      openedAt: at(0, 13, 5),
      session: "ny_am",
      riskPct: 0.5,
      rr: 2,
      result: "tp",
      context: "HTF bullish, discount FVG на 15m, NY AM открытие",
      setup: "Open Drive",
      profitPct: 1.0,
      profitUsd: 1000,
      rMultiple: 2,
      notes: "Чистый drive после свипа азиатского лоя. Держал до 2R, не жадничал.",
      screenshots: shots(11, true, ["M5", "M15", "H1"]),
    },
    {
      id: "t_today_2",
      daysAgo: 0,
      accountId: A1,
      title: "ES Retrace",
      pair: "ES",
      market: "indices",
      side: "short",
      openedAt: at(0, 14, 12),
      session: "ny_am",
      riskPct: 0.4,
      rr: 1.5,
      result: "open",
      context: "Премиум, реакция на сессионный хай",
      setup: "FVG",
      profitPct: 0,
      profitUsd: 0,
      rMultiple: 0,
      notes: "В рынке, стоп за свипом. Цель — лой лондонского продолжения.",
      screenshots: shots(12, false, ["M5", "M15"]),
    },
    {
      id: "t_1",
      daysAgo: 1,
      accountId: A1,
      title: "XAU Silver Bullet",
      pair: "XAUUSD",
      market: "metals",
      side: "long",
      openedAt: at(1, 10, 8),
      session: "ny_am",
      riskPct: 0.5,
      rr: 3,
      result: "tp",
      context: "Киллзон 10:00 NY, бычий FVG",
      setup: "Silver Bullet",
      profitPct: 1.5,
      profitUsd: 1500,
      rMultiple: 3,
      notes: "Классика. Вошёл лимитом в FVG, выход на 3R.",
      screenshots: shots(21, true, ["M1", "M5", "H1"]),
    },
    {
      id: "t_2",
      daysAgo: 1,
      accountId: A3,
      title: "EURUSD MSS",
      pair: "EURUSD",
      market: "forex",
      side: "short",
      openedAt: at(1, 9, 22),
      session: "london",
      riskPct: 0.4,
      rr: 2,
      result: "sl",
      context: "Лондонский свип, ложный MSS",
      setup: "MSS",
      profitPct: -0.4,
      profitUsd: -200,
      rMultiple: -1,
      notes: "Новости CPI вскинули цену. Не торговать за 15 мин до цифр.",
      screenshots: shots(22, false, ["M5", "M15"]),
    },
    {
      id: "t_3",
      daysAgo: 2,
      accountId: A1,
      title: "US30 Breaker",
      pair: "US30",
      market: "indices",
      side: "long",
      openedAt: at(2, 15, 40),
      session: "ny_pm",
      riskPct: 0.5,
      rr: 2,
      result: "tp",
      context: "PM continuation, breaker из утра",
      setup: "Breaker",
      profitPct: 1.0,
      profitUsd: 1000,
      rMultiple: 2,
      notes: "",
      screenshots: shots(31, true, ["M15", "H1"]),
    },
    {
      id: "t_4",
      daysAgo: 3,
      accountId: A1,
      title: "GBPUSD Judas",
      pair: "GBPUSD",
      market: "forex",
      side: "short",
      openedAt: at(3, 8, 15),
      session: "london",
      riskPct: 0.5,
      rr: 2.5,
      result: "be",
      context: "Judas swing лондонского открытия",
      setup: "Judas Swing",
      profitPct: 0,
      profitUsd: 0,
      rMultiple: 0,
      notes: "Перенёс в BE после 1R. Правильно: импульс умер.",
      screenshots: shots(41, false, ["M5", "H1"]),
    },
    {
      id: "t_5",
      daysAgo: 4,
      accountId: A2,
      title: "BTC sweep",
      pair: "BTCUSD",
      market: "crypto",
      side: "long",
      openedAt: at(4, 2, 10),
      session: "asia",
      riskPct: 0.7,
      rr: 2,
      result: "tp",
      context: "Азиатский свип равных лоев",
      setup: "Sweep",
      profitPct: 1.4,
      profitUsd: 175,
      rMultiple: 2,
      notes: "Крипта ночью отрабатывает быстрее. Размер меньше обычного.",
      screenshots: shots(51, true, ["M15", "H4"]),
    },
    {
      id: "t_6",
      daysAgo: 5,
      accountId: A1,
      title: "GER40 OB",
      pair: "GER40",
      market: "indices",
      side: "short",
      openedAt: at(5, 9, 5),
      session: "frankfurt",
      riskPct: 0.5,
      rr: 2,
      result: "sl",
      context: "Франкфурт, премиум OB",
      setup: "Order Block",
      profitPct: -0.5,
      profitUsd: -500,
      rMultiple: -1,
      notes: "Слишком рано. Ждать NY подтверждение.",
      screenshots: shots(61, false, ["M5", "M15"]),
    },
    {
      id: "t_7",
      daysAgo: 6,
      accountId: A1,
      title: "NQ Silver Bullet",
      pair: "NQ",
      market: "indices",
      side: "short",
      openedAt: at(6, 11, 2),
      session: "ny_am",
      riskPct: 0.5,
      rr: 2,
      result: "tp",
      context: "Киллзон, медвежий FVG после CISD",
      setup: "Silver Bullet",
      profitPct: 1.0,
      profitUsd: 1000,
      rMultiple: 2,
      notes: "",
      screenshots: shots(71, false, ["M1", "M5", "H1"]),
    },
    {
      id: "t_8",
      daysAgo: 7,
      accountId: A3,
      title: "XAU News fade",
      pair: "XAUUSD",
      market: "metals",
      side: "short",
      openedAt: at(7, 14, 35),
      session: "ny_pm",
      riskPct: 0.4,
      rr: 1.8,
      result: "tp",
      context: "Fade первого импульса NFP",
      setup: "News Fade",
      profitPct: 0.72,
      profitUsd: 360,
      rMultiple: 1.8,
      notes: "Только после возврата в диапазон.",
      screenshots: shots(81, false, ["M5", "M15"]),
    },
    {
      id: "t_9",
      daysAgo: 8,
      accountId: A1,
      title: "ES OTE",
      pair: "ES",
      market: "indices",
      side: "long",
      openedAt: at(8, 16, 20),
      session: "ny_pm",
      riskPct: 0.5,
      rr: 2,
      result: "tp",
      context: "OTE на 62–79 фибо после MSS",
      setup: "OTE",
      profitPct: 1.0,
      profitUsd: 1000,
      rMultiple: 2,
      notes: "",
      screenshots: shots(91, true, ["M15", "H1"]),
    },
    {
      id: "t_10",
      daysAgo: 9,
      accountId: A1,
      title: "USDJPY SFP",
      pair: "USDJPY",
      market: "forex",
      side: "short",
      openedAt: at(9, 3, 40),
      session: "asia",
      riskPct: 0.4,
      rr: 2,
      result: "sl",
      context: "Азиатский SFP, но тренд сильный",
      setup: "SFP",
      profitPct: -0.4,
      profitUsd: -400,
      rMultiple: -1,
      notes: "Не контрить сильный тренд на азии.",
      screenshots: shots(101, true, ["M15", "H4"]),
    },
    {
      id: "t_11",
      daysAgo: 10,
      accountId: A2,
      title: "ETH BOS",
      pair: "ETHUSD",
      market: "crypto",
      side: "long",
      openedAt: at(10, 21, 10),
      session: "swing",
      riskPct: 1,
      rr: 3,
      result: "tp",
      context: "Дневной BOS, ретест",
      setup: "Break & Retest",
      profitPct: 3,
      profitUsd: 375,
      rMultiple: 3,
      notes: "Свинг. Держал 2 дня.",
      screenshots: shots(111, true, ["H4", "D1"]),
    },
    {
      id: "t_12",
      daysAgo: 11,
      accountId: A1,
      title: "NQ FVG",
      pair: "NQ",
      market: "indices",
      side: "long",
      openedAt: at(11, 10, 18),
      session: "ny_am",
      riskPct: 0.5,
      rr: 2,
      result: "be",
      context: "FVG не удержали",
      setup: "FVG",
      profitPct: 0,
      profitUsd: 0,
      rMultiple: 0,
      notes: "BE — тоже результат.",
      screenshots: shots(121, true, ["M5", "M15"]),
    },
    {
      id: "t_13",
      daysAgo: 13,
      accountId: A1,
      title: "GER40 Open",
      pair: "GER40",
      market: "indices",
      side: "long",
      openedAt: at(13, 8, 5),
      session: "frankfurt",
      riskPct: 0.4,
      rr: 1.5,
      result: "tp",
      context: "Касса Франкфурта, пре-маркет дисконт",
      setup: "Open Drive",
      profitPct: 0.6,
      profitUsd: 600,
      rMultiple: 1.5,
      notes: "",
      screenshots: shots(131, true, ["M5", "M15"]),
    },
    {
      id: "t_14",
      daysAgo: 14,
      accountId: A3,
      title: "GBPUSD OB",
      pair: "GBPUSD",
      market: "forex",
      side: "long",
      openedAt: at(14, 9, 48),
      session: "london",
      riskPct: 0.5,
      rr: 2,
      result: "tp",
      context: "Лондон, дисконтный OB",
      setup: "Order Block",
      profitPct: 1.0,
      profitUsd: 500,
      rMultiple: 2,
      notes: "",
      screenshots: shots(141, true, ["M5", "H1"]),
    },
    {
      id: "t_15",
      daysAgo: 16,
      accountId: A1,
      title: "ES News",
      pair: "ES",
      market: "indices",
      side: "short",
      openedAt: at(16, 14, 5),
      session: "ny_pm",
      riskPct: 0.3,
      rr: 2,
      result: "sl",
      context: "FOMC, контртренд",
      setup: "News Fade",
      profitPct: -0.3,
      profitUsd: -300,
      rMultiple: -1,
      notes: "FOMC не фейдить в первую свечу.",
      screenshots: shots(151, false, ["M1", "M5"]),
    },
    {
      id: "t_16",
      daysAgo: 18,
      accountId: A1,
      title: "XAU OTE",
      pair: "XAUUSD",
      market: "metals",
      side: "long",
      openedAt: at(18, 11, 30),
      session: "ny_am",
      riskPct: 0.5,
      rr: 2.2,
      result: "tp",
      context: "Дисконт после азиатского дистрибьюшена",
      setup: "OTE",
      profitPct: 1.1,
      profitUsd: 1100,
      rMultiple: 2.2,
      notes: "",
      screenshots: shots(161, true, ["M15", "H1", "H4"]),
    },
  ];

  return rows.map(({ daysAgo: _d, ...t }) => ({
    ...t,
    createdAt: t.openedAt,
  }));
}

export function buildSeedPlans(): Plan[] {
  const today = todayISO();
  const d = new Date();
  const day = d.getDay();
  const mondayOffset = day === 0 ? 6 : day - 1;
  const monday = new Date(d);
  monday.setDate(d.getDate() - mondayOffset);
  const week = todayISO(monday);

  return [
    {
      id: "plan_day",
      period: "day",
      date: today,
      bias: "Bullish indices, gold range",
      focusPairs: ["NQ", "ES", "XAUUSD"],
      maxTrades: 2,
      maxRiskPct: 1,
      rules: [
        "Только NY AM и Silver Bullet",
        "Нет новостей за 20 минут",
        "BE после 1R, если структура ломается",
      ],
      notes: "Жду дисконт на NQ. Если азия закрыла выше, не шортить первое касание.",
    },
    {
      id: "plan_week",
      period: "week",
      date: week,
      bias: "Risk-on, DXY слабый",
      focusPairs: ["NQ", "GER40", "XAUUSD", "EURUSD"],
      maxTrades: 8,
      maxRiskPct: 3,
      rules: [
        "Индексы в приоритете",
        "Золото только от H1 OB",
        "Максимум 2 убытка подряд — стоп на день",
      ],
      notes: "Неделя отчётности. Срезать риск в среду.",
    },
  ];
}

export function createSeed(): JournalSnapshot & { selectedDate: string } {
  return {
    profile: { name: "Anowar", avatarSrc: null },
    appearance: { ...DEFAULT_APPEARANCE },
    accounts: SEED_ACCOUNTS,
    activeAccountId: A1,
    trades: buildSeedTrades(),
    plans: buildSeedPlans(),
    selectedDate: todayISO(),
  };
}

export function emptySnapshot(): JournalSnapshot & { selectedDate: string } {
  const accId = uid();
  return {
    profile: { name: "Trader", avatarSrc: null },
    appearance: { ...DEFAULT_APPEARANCE },
    accounts: [
      {
        id: accId,
        name: "Main",
        firm: "Personal",
        type: "personal",
        currency: "USD",
        startBalance: 10000,
        profitTargetPct: 0,
        maxDrawdownPct: 10,
        dailyLossPct: 2,
      },
    ],
    activeAccountId: accId,
    trades: [],
    plans: [],
    selectedDate: todayISO(),
  };
}
