/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TradeIdRouteImport } from './routes/trade.$id'
import { Route as TradeNewRouteImport } from './routes/trade.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIdRoute = TradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeNewRoute = TradeNewRouteImport.update({
  id: '/trade/new',
  path: '/trade/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trade/$id': typeof TradeIdRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trade/$id': typeof TradeIdRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/stats': typeof StatsRoute
  '/trade/$id': typeof TradeIdRoute
  '/trade/new': typeof TradeNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal'
    | '/plan'
    | '/profile'
    | '/share'
    | '/stats'
    | '/trade/$id'
    | '/trade/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journal'
    | '/plan'
    | '/profile'
    | '/share'
    | '/stats'
    | '/trade/$id'
    | '/trade/new'
  id:
    | '__root__'
    | '/'
    | '/journal'
    | '/plan'
    | '/profile'
    | '/share'
    | '/stats'
    | '/trade/$id'
    | '/trade/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  ShareRoute: typeof ShareRoute
  StatsRoute: typeof StatsRoute
  TradeIdRoute: typeof TradeIdRoute
  TradeNewRoute: typeof TradeNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$id': {
      id: '/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof TradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/new': {
      id: '/trade/new'
      path: '/trade/new'
      fullPath: '/trade/new'
      preLoaderRoute: typeof TradeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  ShareRoute: ShareRoute,
  StatsRoute: StatsRoute,
  TradeIdRoute: TradeIdRoute,
  TradeNewRoute: TradeNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
